### ISSUE TITLE
bug: doctrine.dbal.default_connection is mandatory

### ISSUE THREAD

**Issue by pierreboissinot** [le-phare/import-bundle#20]
In a project not using an URL in dbal configuration:

```yaml
doctrine:
    dbal:
        driver: 'pdo_pgsql'
        # See https://symfony.com/doc/current/doctrine.html#configuring-the-database
        dbname: '%env(resolve:DATABASE_NAME)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '5432'
        charset: 'utf8'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
```

There is a fatal error due to this line

https://github.com/le-phare/import-bundle/blob/d62512a28cbac6b6bda55f91a13741ec9205d961/DependencyInjection/Compiler/CredentialsConfigurationPass.php#L21

![Screenshot from 2024-12-06 16-20-00](https://github.com/user-attachments/assets/7e47610e-a27b-4bce-ac99-7e392784385c)
